### ISSUE TITLE
Discussion: splitting some of this up into modules

### ISSUE THREAD

**Issue by JakeHartnell** [w3c/web-of-things-framework#75]
First of all, there are lot's of great things happening here, but arguably it would be much more useful if we could talk about how to start splitting it up into more reusable npm modules.

As a starting point I've mocked up an example of the type of modules I would like to see, checkout [Thing.js](http://commongarden.github.io/Thing.js/docs/). It has a small scope: a simple class for constructing and working with Thing objects that contain metadata, events, properties, and actions.

It would be great to start seeing similarly scoped modules for things like secure device configuration, discovery, etc. There are many parts to an IoT framework, as such it might be helpful to start discussing how we can break this framework up into it's core components.

Thoughts?

**Comment by zsoltpardi** [comment]
You are absolutely right and we should start breaking up the solution into modules. We have been discussing this for a while and it has been identified we should do this, and it would be great to make actual progress in this area.

Terms of the Thing.js implementation, it would be great if such npm module would be available.  
With regards to the implementation, please but one of the premises in WoT that thing is defined using JSON-LD definition, and then the application parses the definition and initialize thing objects based on the JSON-LD definition. I think the Thing.js you propose should work the same way. You can refer to the the source code (thing.js) to review how the JSON-LD data structure is parsed and properties, actions and events are initiated based on it. I am sure the parsing and object initialization can be done more efficiently or there is a better way to code those functions, so we can change that, but conceptually the idea is to have a JSON-LD definition for things.

**Comment by JakeHartnell** [comment]
> Terms of the Thing.js implementation, it would be great if such npm module would be available.

Let's make one then!

Please feel free to fork Thing.js, open issues, or start over with a new version. A JSON-LD definition of things would be cool, but I think the key is a tightly scoped library for parsing and object initialization.  Ideally, it would be as simple as passing a configuration object to a constructor.

I'm using Thing.js in another library called [Grow.js](https://github.com/CommonGarden/Grow.js) which connects to a meteor application called [Grow-IoT](https://github.com/CommonGarden/Grow-IoT). I would start using the web of things framework right now if it was in similarly tightly scoped module.

**Comment by JakeHartnell** [comment]
> You are absolutely right and we should start breaking up the solution into modules. We have been discussing this for a while and it has been identified we should do this, and it would be great to make actual progress in this area.

Other suggestions for things we could break out?

**Comment by zsoltpardi** [comment]
> Let's make one then!
Please feel free to fork Thing.js, open issues, or start over with a new version. A JSON-LD definition of things would be cool, but I think the key is a tightly scoped library for parsing and object initialization. Ideally, it would be as simple as passing a configuration object to a constructor.

I meant to say, it would be great to create such JSON-LD based thing handler here, as part of this project and then make it available as an npm package, so other IoT projects could reuse the thing handler module of the W3C web-of-things-framework. 
One of the main objectives of the W3C WoT project is to provide developers with a tool to speed up IoT development. Thing definition and thing initialization is the core element of such solution and it should be part of this project instead of developing somewhere else and then referencing it from the package.json configuration file. This project reuses many third party libraries and gives the well deserved credit to to their developers, but the web-of-things framework which primary purpose is to handle things should implement at least the thing handler as part of this project. 
If the Thing.js can be initialized using JSON-LD and it is better than our current thing handler than it is a good idea to replace our current thing handler with a Thing.js based design/implementation, but the source code should be part of this project. This way we can keep the core functionality thing handling within this project.
Please feel free to make any changes and pull requests in this project, and we will decide together how to proceed. Then in next step we will decide together how to break up the current structure into sub projects or modules to create NPM packages from it.
